const galleryPlaneData = [
  {
    textureSrc: "/images/performers-gallery/kimmi-k.webp",
    position: { x: -0.9, y: 0 },
    fallbackColor: "#53a9dc",
    accentColor: "#53a9dc",
    backgroundColor: "#0d1b24",
    blob1Color: "#53a9dc",
    blob2Color: "#e6007e",
    label: { word: "Kimmi K" },
  },
  {
    textureSrc: "/images/performers-gallery/dior.webp",
    position: { x: 0.8, y: 0 },
    fallbackColor: "#4d0026",
    accentColor: "#e6007e",
    backgroundColor: "#170b0d",
    blob1Color: "#e6007e",
    blob2Color: "#4d0026",
    label: { word: "Dior" },
  },
  {
    textureSrc: "/images/performers-gallery/lotus.webp",
    position: { x: -0.7, y: 0 },
    fallbackColor: "#d9a066",
    accentColor: "#d9a066",
    backgroundColor: "#15111a",
    blob1Color: "#d9a066",
    blob2Color: "#e6007e",
    label: { word: "Lotus" },
  },
  {
    textureSrc: "/images/performers-gallery/sexy-nurse.webp",
    position: { x: 0.9, y: 0 },
    fallbackColor: "#ff3b3b",
    accentColor: "#ff3b3b",
    backgroundColor: "#1c0507",
    blob1Color: "#ff3b3b",
    blob2Color: "#e6007e",
    label: { word: "Sexy Nurse" },
  },
  {
    textureSrc: "/images/performers-gallery/bad-cop.webp",
    position: { x: -0.6, y: 0 },
    fallbackColor: "#274472",
    accentColor: "#274472",
    backgroundColor: "#070b14",
    blob1Color: "#274472",
    blob2Color: "#e6007e",
    label: { word: "Bad Cop" },
  },
];

export { galleryPlaneData };
